### PR TITLE
add cmake support

### PR DESCRIPTION
**Pull request by kostyfisik**
Add cmake support to FiNeR. It rely on https://github.com/szaghi/BeFoR64/pull/13 and https://github.com/szaghi/FLAP/pull/88, the config is adapted from PENF project after @lettleli

### CODE REVIEW

**Comment by szaghi** [comment]
@kostyfisik Hi Konstantin, I am not able to merge this pull request, can you help me?

**Comment by kostyfisik** [comment]
@szaghi Could you please update all third_party dependencies? When I freshly clone my cmake branch and chekout all third_party to their master branches it works fine.

**Comment by szaghi** [comment]
@kostyfisik third party updated

**Comment by szaghi** [comment]
@kostyfisik Thanks!

**Comment by kostyfisik** [comment]
@szaghi I shill wonder what I have done so it started to work :)

**Comment by kostyfisik** [comment]
@szaghi See the updated https://github.com/szaghi/FiNeR/wiki/Compile#compiling-by-means-of-cmake

**Comment by szaghi** [comment]
@kostyfisik thank you very much!

**Pull request merged**
